### ISSUE TITLE
### Test and Deploy

### ISSUE THREAD

**Issue by geekwise-alfredo-diaz** [geekwise-alfredo-diaz/django-drf-react-todo#2]
> Test app to see if it works locally
> Figure out how to deploy to Heroku
- Not able to have db sync in heroku or run migrations
- Issue: No module named 'backened.backend'

**Comment by climateamante** [comment]
@FredoDiaz 

Can you update your project board and readme file?
Also, feel free to checkout the repo from @geekwise-estefania-flores 
It has some solutions to where I last saw your status on the project.

Thank you.
