### ISSUE TITLE
Suggestion: Missing `.results` after `res.data`

### ISSUE THREAD

**Issue by geekwise-ashkan-nadiri** [geekwise-alfredo-diaz/django-drf-react-todo#5]
[take a look at line 24](https://github.com/geekwise-alfredo-diaz/django-drf-react-todo/blob/657bd9d5250b7a2e076f885768e00b1e37c384da/frontend/src/App.js#L24)

**Comment by geekwise-alfredo-diaz** [comment]
Fixed the issue. Goolook'n out!
